# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Feldenkrais"
pageRef = "feldenkrais"
weight = 10

[[main]]
name = "Jóga"
pageRef = "joga"
weight = 20

[[main]]
name = "Kde a kdy"
pageRef = "rozvrh"
weight = 30

[[main]]
name = "Kurzy"
pageRef = "kurzy"
weight = 40

[[main]]
name = "Ceník"
pageRef = "cenik"
weight = 50

[[main]]
name = "O mně"
pageRef = "o-mne"
weight = 60

[[main]]
name = "Kontakt"
pageRef = "kontakt"
weight = 70

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Kontakt"
pageRef = "kontakt"
weight = 70

[[footer]]
name = "Ceník"
pageRef = "cenik"
weight = 50